import { v } from "convex/values";
import { mutation, query } from "./_generated/server";

// Save learning plan (curriculum generated by AI on frontend)
export const saveLearningPlan = mutation({
  args: {
    learningRequestId: v.id("learningRequests"),
    curriculum: v.object({
      modules: v.array(
        v.object({
          title: v.string(),
          description: v.optional(v.string()),
          estimatedDurationMinutes: v.number(),
          objectives: v.array(v.string()),
          lessons: v.array(
            v.object({
              title: v.string(),
              description: v.optional(v.string()),
              estimatedDurationMinutes: v.number(),
              keyPoints: v.array(v.string()),
            })
          ),
        })
      ),
    }),
  },
  returns: v.id("learningRequests"),
  async handler(ctx, args) {
    // Get the learning request
    const request = await ctx.db.get(args.learningRequestId);
    if (!request) throw new Error("Learning request not found");

    // Create modules and lessons
    for (let moduleIdx = 0; moduleIdx < args.curriculum.modules.length; moduleIdx++) {
      const mod = args.curriculum.modules[moduleIdx];
      const moduleId = await ctx.db.insert("learning_modules", {
        learningRequestId: args.learningRequestId,
        title: mod.title,
        description: mod.description,
        order: moduleIdx + 1,
        estimatedDurationMinutes: mod.estimatedDurationMinutes,
        objectives: mod.objectives,
        difficultyLevel:
          request.experienceLevel === "beginner"
            ? "beginner"
            : request.experienceLevel === "intermediate"
            ? "intermediate"
            : "advanced",
        createdAt: Date.now(),
      });

      // Create lessons for this module
      for (let lessonIdx = 0; lessonIdx < mod.lessons.length; lessonIdx++) {
        const lesson = mod.lessons[lessonIdx];
        await ctx.db.insert("learning_lessons", {
          moduleId,
          learningRequestId: args.learningRequestId,
          title: lesson.title,
          description: lesson.description,
          order: lessonIdx + 1,
          estimatedDurationMinutes: lesson.estimatedDurationMinutes,
          keyPoints: lesson.keyPoints,
          createdAt: Date.now(),
        });
      }
    }

    // Update request status to "active"
    await ctx.db.patch(args.learningRequestId, {
      status: "active",
      updatedAt: Date.now(),
    });

    return args.learningRequestId;
  },
});

// Get learning plan with all modules and lessons
export const getLearningPlan = query({
  args: {
    learningRequestId: v.id("learningRequests"),
  },
  returns: v.object({
    request: v.object({
      skill: v.string(),
      learningGoal: v.string(),
      status: v.string(),
    }),
    modules: v.array(
      v.object({
        _id: v.id("learning_modules"),
        title: v.string(),
        description: v.optional(v.string()),
        order: v.number(),
        estimatedDurationMinutes: v.number(),
        objectives: v.array(v.string()),
        lessons: v.array(
          v.object({
            _id: v.id("learning_lessons"),
            title: v.string(),
            description: v.optional(v.string()),
            order: v.number(),
            estimatedDurationMinutes: v.number(),
            keyPoints: v.array(v.string()),
          })
        ),
      })
    ),
    totalEstimatedMinutes: v.number(),
  }),
  async handler(ctx, args) {
    const request = await ctx.db.get(args.learningRequestId);
    if (!request) throw new Error("Learning request not found");

    const modules = await ctx.db
      .query("learning_modules")
      .withIndex("by_learning_request", (q: any) =>
        q.eq("learningRequestId", args.learningRequestId)
      )
      .collect();

    const modulesWithLessons = await Promise.all(
      modules.map(async (mod: any) => {
        const lessons = await ctx.db
          .query("learning_lessons")
          .withIndex("by_module", (q: any) => q.eq("moduleId", mod._id))
          .collect();

        return {
          _id: mod._id,
          title: mod.title,
          description: mod.description,
          order: mod.order,
          estimatedDurationMinutes: mod.estimatedDurationMinutes,
          objectives: mod.objectives,
          lessons: lessons.map((l: any) => ({
            _id: l._id,
            title: l.title,
            description: l.description,
            order: l.order,
            estimatedDurationMinutes: l.estimatedDurationMinutes,
            keyPoints: l.keyPoints,
          })),
        };
      })
    );

    const totalEstimatedMinutes = modulesWithLessons.reduce(
      (sum: number, mod: any) => sum + mod.estimatedDurationMinutes,
      0
    );

    return {
      request: {
        skill: request.skill,
        learningGoal: request.learningGoal,
        status: request.status,
      },
      modules: modulesWithLessons,
      totalEstimatedMinutes,
    };
  },
});
