import React, { useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  ActivityIndicator,
  Alert,
  Linking,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MaterialIcons } from '@expo/vector-icons';
import { useMutation, useQuery } from 'convex/react';
import { api } from '../lib/config';
import type { Id } from '../lib/config';
import { colors, spacing, radius, typography, shadows } from '../lib/theme';
import { AuthContext } from '../lib/auth-context';
import { useBranding } from '../lib/branding-context';

type Props = {
  onClose?: () => void;
  companyId: Id<'companies'>;
  userId: Id<'users'>;
  packagePlan?: 'starter' | 'pro' | 'enterprise';
};

type PackageItem = {
  plan: 'starter' | 'pro' | 'enterprise';
  name: string;
  price: number;
  maxEmployees: number;
  maxGroups: number;
  features: string[];
  isCurrentPlan: boolean;
  canDowngradeTo: boolean;
  canUpgradeTo: boolean;
  reason?: string;
};

type EFTResult = {
  paymentId: string;
  paymentReference: string;
  referenceSource: string;
  companyName: string;
  userEmail: string;
  amount: number;
  currency: string;
  packageName: string;
  maxEmployees: number;
  maxEmployeeGroups: number;
  features: string[];
  bankingDetails: {
    bankName: string;
    branchName: string;
    branchCode: string;
    accountHolder: string;
    accountNumber: string;
    accountType: string;
    swiftCode: string;
  };
  expiresAt: number;
  whatsappLink: string;
};

export default function EFTPaymentScreen({ onClose, companyId, userId, packagePlan }: Props) {
  const auth = useContext(AuthContext);
  const { branding } = useBranding();
  if (!auth) {
    throw new Error('AuthProvider missing');
  }

  const { signOut } = auth;
  const clientName = branding.displayName || branding.brandStatement || 'Your company';
  const supportEmail = branding.supportEmail;
  const packages = useQuery(api.packages.getAvailablePackages, companyId ? { companyId } : 'skip') as PackageItem[] | undefined;
  const initiateEFTPayment = useMutation(api.eft.initiateEFTPayment);
  const submitEFTPaymentForReview = useMutation(api.eft.submitEFTPaymentForReview);
  const [selectedPlan, setSelectedPlan] = useState<'starter' | 'pro' | 'enterprise'>(packagePlan ?? 'starter');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [payment, setPayment] = useState<EFTResult | null>(null);
  const autoGeneratedPlanRef = useRef<'starter' | 'pro' | 'enterprise' | null>(null);
  const canGeneratePayment = Boolean(companyId && userId);

  const selectedPackage = useMemo(
    () => packages?.find((item) => item.plan === selectedPlan),
    [packages, selectedPlan]
  );

  useEffect(() => {
    if (packagePlan && packagePlan !== selectedPlan) {
      setSelectedPlan(packagePlan);
      setPayment(null);
    }
  }, [packagePlan, selectedPlan]);

  const generatePayment = useCallback(async (plan: 'starter' | 'pro' | 'enterprise') => {
    if (!canGeneratePayment) {
      Alert.alert(
        'Account not ready',
        'Your company details are still loading. Please go back and open EFT again.'
      );
      return;
    }

    setIsGenerating(true);
    try {
      const result = await initiateEFTPayment({
        companyId,
        userId,
        packagePlan: plan,
      });
      setPayment(result as EFTResult);
    } catch (e: any) {
      Alert.alert('Payment setup failed', e?.message || 'Unable to create EFT instructions');
    } finally {
      setIsGenerating(false);
    }
  }, [canGeneratePayment, companyId, initiateEFTPayment, userId]);

  useEffect(() => {
    if (!canGeneratePayment || payment || isGenerating) return;
    if (autoGeneratedPlanRef.current === selectedPlan) return;

    autoGeneratedPlanRef.current = selectedPlan;
    void generatePayment(selectedPlan);
  }, [canGeneratePayment, generatePayment, isGenerating, payment, selectedPlan]);


  const handleWhatsApp = async () => {
    if (!payment) return;
    try {
      await Linking.openURL(payment.whatsappLink);
    } catch {
      Alert.alert('Error', 'Could not open WhatsApp');
    }
  };

  const handleEmailProof = async () => {
    if (!payment) return;
    const supportEmail = branding.supportEmail;
    if (!supportEmail) {
      Alert.alert('Email not available', 'Email proof is not configured for this account yet.');
      return;
    }

    const subject = encodeURIComponent(`Payment proof - ${payment.companyName}`);
    const body = encodeURIComponent(
      `Hi,\n\nI have made payment for the ${payment.packageName} package.\n\nCompany: ${payment.companyName}\nEmail: ${payment.userEmail}\nReference: ${payment.paymentReference}\nAmount: R${payment.amount}\n\nPlease find my proof of payment attached in the email reply.\n`
    );

    try {
      await Linking.openURL(`mailto:${supportEmail}?subject=${subject}&body=${body}`);
    } catch {
      Alert.alert('Error', 'Could not open email');
    }
  };

  const handleSubmitToAdmin = async () => {
    if (!payment) return;
    setIsSubmitting(true);
    try {
      const result = await submitEFTPaymentForReview({ paymentId: payment.paymentId });
      Alert.alert('Sent to admin', result.message);
    } catch (e: any) {
      Alert.alert('Submission failed', e?.message || 'Could not send payment to admin');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <SafeAreaView style={styles.container} edges={['top', 'bottom']}>
      <View style={styles.header}>
        <View>
          <Text style={styles.kicker}>Bank Transfer</Text>
          <Text style={styles.title}>EFT payment instructions</Text>
        </View>
        <View style={styles.headerActions}>
          <TouchableOpacity onPress={signOut} style={styles.iconButton}>
            <MaterialIcons name="logout" size={22} color={colors.textSecondary} />
          </TouchableOpacity>
          {onClose ? (
            <TouchableOpacity onPress={onClose} style={styles.iconButton}>
              <MaterialIcons name="close" size={24} color={colors.text} />
            </TouchableOpacity>
          ) : null}
        </View>
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.heroCard}>
          <Text style={styles.heroTitle}>Manual activation flow</Text>
          <Text style={styles.heroText}>
            Pay by EFT, use the reference below, then send your proof of payment by WhatsApp or email. The admin will review and activate your package.
          </Text>
        </View>

        {!packages ? (
          <View style={styles.loadingCard}>
            <ActivityIndicator size="large" color={colors.primary} />
            <Text style={styles.loadingText}>Loading package details…</Text>
          </View>
        ) : (
          <View style={styles.selectionGrid}>
            {packages.map((pkg) => {
              const isActive = pkg.plan === selectedPlan;
              return (
                <TouchableOpacity
                  key={pkg.plan}
                  style={[styles.selectionCard, isActive && styles.selectionCardActive]}
                  onPress={() => {
                    setSelectedPlan(pkg.plan);
                    setPayment(null);
                  }}
                >
                  <Text style={styles.selectionName}>{pkg.name}</Text>
                  <Text style={styles.selectionMeta}>R{pkg.price} • {pkg.maxEmployees} users</Text>
                </TouchableOpacity>
              );
            })}
          </View>
        )}

        {isGenerating && !payment ? (
          <View style={styles.loadingCard}>
            <ActivityIndicator size="large" color={colors.primary} />
            <Text style={styles.loadingText}>Generating EFT reference…</Text>
          </View>
        ) : payment ? (
          <View style={styles.paymentCard}>
            <View style={styles.amountRow}>
              <View>
                <Text style={styles.paymentLabel}>Amount</Text>
                <Text style={styles.amountValue}>R{payment.amount}</Text>
              </View>
              <View style={styles.statusPill}>
                <Text style={styles.statusPillText}>Awaiting verification</Text>
              </View>
            </View>

            <View style={styles.detailBox}>
              <Text style={styles.detailLabel}>Payment reference</Text>
              <Text style={styles.detailValueMono}>{payment.paymentReference}</Text>
              <Text style={styles.detailHint}>Short reference: {payment.paymentReference}</Text>
              <Text style={styles.detailHint}>Reference source: {payment.referenceSource}</Text>
              <Text style={styles.detailHint}>Company: {payment.companyName}</Text>
              <Text style={styles.detailHint}>Email: {payment.userEmail}</Text>
              <Text style={styles.detailHint}>Branding: {clientName}</Text>
              <Text style={styles.detailHint}>Use the exact short reference above when making the bank transfer.</Text>
            </View>

            <View style={styles.detailBox}>
              <Text style={styles.detailLabel}>Contact for proof</Text>
              <Text style={styles.detailHint}>
                If you do not use WhatsApp, send your proof by email{supportEmail ? ` to ${supportEmail}` : ''}.
              </Text>
            </View>

            <View style={styles.detailBox}>
              <Text style={styles.detailLabel}>Bank details</Text>
              <Text style={styles.detailValue}>{payment.bankingDetails.bankName}</Text>
              <Text style={styles.detailHint}>{payment.bankingDetails.branchName} • {payment.bankingDetails.branchCode}</Text>
              <Text style={styles.detailHint}>Account: {payment.bankingDetails.accountNumber}</Text>
              <Text style={styles.detailHint}>Account holder: {payment.bankingDetails.accountHolder}</Text>
              <Text style={styles.detailHint}>Type: {payment.bankingDetails.accountType}</Text>
            </View>

            <View style={styles.detailBox}>
              <Text style={styles.detailLabel}>Next step</Text>
              <Text style={styles.detailHint}>
                After payment, press "I have paid - send to admin" then send your proof of payment on WhatsApp or by email.
              </Text>
            </View>

            <TouchableOpacity
              style={[styles.primaryButton, isSubmitting && styles.primaryButtonDisabled]}
              onPress={handleSubmitToAdmin}
              disabled={isSubmitting}
            >
              <MaterialIcons name="send" size={20} color={colors.background} />
              <Text style={styles.primaryButtonText}>
                {isSubmitting ? 'Sending…' : 'I have paid - send to admin'}
              </Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={styles.whatsappButton}
              onPress={handleWhatsApp}
            >
              <MaterialIcons name="whatsapp" size={20} color={colors.background} />
              <Text style={styles.whatsappButtonText}>Send proof on WhatsApp</Text>
            </TouchableOpacity>

            <TouchableOpacity
              style={styles.emailButton}
              onPress={handleEmailProof}
            >
              <MaterialIcons name="email" size={20} color={colors.background} />
              <Text style={styles.emailButtonText}>Send proof by email</Text>
            </TouchableOpacity>
          </View>
        ) : (
          <TouchableOpacity
            style={styles.primaryButton}
            onPress={() => void generatePayment(selectedPlan)}
          >
            <MaterialIcons name="account-balance" size={20} color={colors.background} />
            <Text style={styles.primaryButtonText}>Generate EFT instructions</Text>
          </TouchableOpacity>
        )}

        {selectedPackage ? (
          <View style={styles.summaryCard}>
            <Text style={styles.summaryTitle}>{selectedPackage.name}</Text>
            <Text style={styles.summaryText}>{selectedPackage.maxEmployees} users • {selectedPackage.maxGroups} groups</Text>
          </View>
        ) : null}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  kicker: { ...typography.caption, color: colors.primary, textTransform: 'uppercase', letterSpacing: 1 },
  title: { ...typography.h3, color: colors.text, marginTop: 2 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  iconButton: {
    padding: spacing.sm,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
  },
  content: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  heroCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.sm,
  },
  heroTitle: { ...typography.h4, color: colors.text },
  heroText: { ...typography.body, color: colors.textSecondary, marginTop: spacing.sm },
  loadingCard: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    paddingVertical: spacing.xl,
  },
  loadingText: { ...typography.body, color: colors.textSecondary },
  selectionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  selectionCard: {
    flexGrow: 1,
    minWidth: 92,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  selectionCardActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary + '10',
  },
  selectionName: { ...typography.bodyMedium, color: colors.text, fontWeight: '700' },
  selectionMeta: { ...typography.caption, color: colors.textSecondary, marginTop: spacing.xs },
  paymentCard: {
    backgroundColor: colors.background,
    borderRadius: radius.xl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.md,
    ...shadows.sm,
  },
  amountRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  paymentLabel: { ...typography.caption, color: colors.textSecondary, fontWeight: '700' },
  amountValue: { ...typography.h2, color: colors.text, marginTop: 2 },
  statusPill: {
    backgroundColor: colors.warning + '18',
    borderRadius: radius.full,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
  },
  statusPillText: { ...typography.caption, color: colors.warning, fontWeight: '700' },
  detailBox: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 4,
  },
  detailLabel: { ...typography.caption, color: colors.textSecondary, fontWeight: '700', marginBottom: 4 },
  detailValue: { ...typography.body, color: colors.text, fontWeight: '600' },
  detailValueMono: { ...typography.body, color: colors.text, fontWeight: '700', fontFamily: 'monospace' },
  detailHint: { ...typography.caption, color: colors.textSecondary },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: radius.lg,
    paddingVertical: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: { ...typography.body, color: colors.background, fontWeight: '700' },
  whatsappButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#25D366',
    borderRadius: radius.lg,
    paddingVertical: spacing.md,
    gap: spacing.sm,
  },
  whatsappButtonText: { ...typography.body, color: colors.background, fontWeight: '700' },
  emailButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.secondary,
    borderRadius: radius.lg,
    paddingVertical: spacing.md,
    gap: spacing.sm,
  },
  emailButtonText: { ...typography.body, color: colors.background, fontWeight: '700' },
  summaryCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  summaryTitle: { ...typography.body, color: colors.text, fontWeight: '700' },
  summaryText: { ...typography.caption, color: colors.textSecondary, marginTop: spacing.xs },
});
